---
# tasks file for db_setup
- name: Update CentOS packages
  yum:
    name: '*'
    state: latest

- name: Install dependencies
  yum:
    name:
     - mariadb-server
     - python3-PyMySQL
     - epel-release
     - git
     - zip
     - unzip
    state: present

- name: Start the DB service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Clone Application Repository
  git:
    repo: https://github.com/spring-petclinic/spring-framework-petclinic.git
    dest: /tmp/spring-framework-petclinic

- name: Create a Database 'petclinic'
  community.mysql.mysql_db:
    name: "{{dbname}}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create admin user and assign privileges of 'petclinic' DB
  community.mysql.mysql_user:
    name: "{{dbuser}}"
    password: "{{dbpass}}"
    host: "%"
    priv: "petclinic.*:ALL"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: Delete remote MySQL users
  shell: "mysql -u root -p'{{ dbpass }}' -e \"DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')\""

- name: Delete anonymous MySQL users
  shell: "mysql -u root -p'{{ dbpass }}' -e \"DELETE FROM mysql.user WHERE User=''\""

- name: Delete test databases
  shell: "mysql -u root -p'{{ dbpass }}' -e \"DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'\""

- name: Flush MySQL privileges
  shell: "mysql -u root -p'{{ dbpass }}' -e \"FLUSH PRIVILEGES\""

- name: Import schema.sql into petclinic database
  shell: "mysql -u root -p'{{ dbpass }}' petclinic < /tmp/spring-framework-petclinic/src/main/resources/db/mysql/schema.sql"

- name: Import data.sql into petclinic database
  shell: "mysql -u root -p'{{ dbpass }}' petclinic < /tmp/spring-framework-petclinic/src/main/resources/db/mysql/data.sql"

- name: Flush MySQL privileges after importing data
  shell: "mysql -u root -p'{{ dbpass }}' -e \"FLUSH PRIVILEGES\""

- name: Restart mariadb-server
  ansible.builtin.service:
    name: mariadb
    state: restarted


