---
- name: DBServer Setup
  hosts: dbserver #group of DBservers
  become: yes 
  tasks:
    -name: Install mariadb-server
     ansible.builtin.yum:
       name: mariadb-server
       state: present
    -name: Start the DB service
     ansible.builtin.service:
       name: mariadb-server
       state: started
       enabled: yes
    -name: Create a Database 'accounts'
     mysql_db: #needs the python dependencies to work
        name: accounts
        state: present